Exercise 1: Create a 4X2 integer array and Prints its attributes



In [21]:
import numpy as np
array = np.array([1,2,3,4,5,6,7,8])


array_new = array.reshape(4,2)
print(array_new)
print(array_new.shape)
print(array_new.ndim)
print(array_new.itemsize)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
2
4


Exercise 2: Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [25]:
array2= np.array([range(100,200,10)])
array2_new= array2.reshape(5,2)
array2_new

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

Exercise 3: Following is the provided numPy array. return array of items in the third column from all rows

In [32]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

array3=np.array([sampleArray[0][1],sampleArray[1][1],sampleArray[2][1]])
print(sampleArray)
print('the elements on the 3rd column are',array3)

[[11 22 33]
 [44 55 66]
 [77 88 99]]
the elements on the 3rd column are [22 55 88]


Exercise 4: Following is the given numpy array return array of odd rows and even columns

In [64]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

list1=[]
for i in range(1,6):
    for j in range(1,6):
        if i%2 != 0 and j%2 == 0:
            
            a=sampleArray[i-1][j-1]
            list1.append(a)
            print(a)
            
a_array = np.array(list1)
print(a_array.reshape(3,2))

6
12
30
36
54
60
[[ 6 12]
 [30 36]
 [54 60]]


In [62]:
type(a_array)

numpy.ndarray